# -*- coding: utf-8 -*-
"""HUels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kd9IyUjugz3n2xkdiyM7ytOljppRekmK
"""

!pip install pdfplumber faiss-cpu sentence-transformers google-generativeai tqdm

import os
os.environ["GEMINI_API_KEY"] = input("Enter your Gemini API Key: ")

"""
rag_backend.py

Clean backend for Development Theory RAG system.

- Local embeddings: sentence-transformers (all-MiniLM-L6-v2)
- Retrieval: FAISS (IndexFlatL2)
- Generation: Gemini (gemini-2.5-flash) via google.generativeai (only for generation)
- Text sources (already uploaded by you):
    TEXTBOOK_PATH = '/mnt/data/Understanding Development.pdf'
    PAPERS_ZIP_PATH = '/mnt/data/DevT_Papers.zip'
"""

import os
import zipfile
import json
from pathlib import Path
from typing import List, Tuple, Optional
import re

# Local file paths (provided by you)
TEXTBOOK_PATH = '/content/Understanding Development.pdf'
PAPERS_ZIP_PATH = '/content/DevT_Papers.zip'

# Vectorstore directory
VECTORSTORE_DIR = '/content/rag_vectorstore'
os.makedirs(VECTORSTORE_DIR, exist_ok=True)

# RAG parameters
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K = 4

# Optional: set env var GEMINI_API_KEY for generation (do not hardcode)
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

# ---------------------------
# Utilities: PDF extraction & chunking
# ---------------------------
import pdfplumber

def extract_text_from_pdf(pdf_path: str) -> str:
    """Extract full text from a PDF file."""
    text_parts = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:
                text_parts.append(text)
    return "\n\n".join(text_parts)

def chunk_text(text: str, chunk_size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> List[dict]:
    """Deterministic whitespace tokenizer chunker -> list of {'id','text','meta'}."""
    tokens = text.split()
    chunks = []
    idx = 0
    chunk_id = 0
    while idx < len(tokens):
        chunk_tokens = tokens[idx: idx + chunk_size]
        chunk_text = ' '.join(chunk_tokens)
        chunks.append({
            'id': f'textbook_chunk_{chunk_id}',
            'text': chunk_text,
            'meta': {'source': TEXTBOOK_PATH, 'chunk': chunk_id}
        })
        chunk_id += 1
        idx += chunk_size - overlap
    return chunks

def extract_texts_from_zip(zip_path: str, extract_to: str = '/content/papers_extracted') -> List[Tuple[str, str]]:
    """Unzip and extract plain text from PDFs and .txt inside the zip. Returns list of (filepath, text)."""
    os.makedirs(extract_to, exist_ok=True)
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(extract_to)

    results = []
    for root, _, files in os.walk(extract_to):
        for fname in files:
            full = os.path.join(root, fname)
            if fname.lower().endswith('.pdf'):
                try:
                    text = extract_text_from_pdf(full)
                    results.append((full, text))
                except Exception as e:
                    print('Failed to read PDF', full, e)
            elif fname.lower().endswith('.txt'):
                try:
                    with open(full, 'r', encoding='utf-8', errors='ignore') as f:
                        results.append((full, f.read()))
                except Exception as e:
                    print('Failed to read txt', full, e)
    return results

# ---------------------------
# Embeddings: sentence-transformers local
# ---------------------------
import numpy as np

class Embedder:
    """Local sentence-transformers embedder using all-MiniLM-L6-v2."""
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        from sentence_transformers import SentenceTransformer
        self.model = SentenceTransformer(model_name)

    def embed_texts(self, texts: List[str]) -> List[np.ndarray]:
        """Return list of numpy float32 vectors for given texts."""
        # `encode` supports a list to batch; ensure result is 2D
        embs = self.model.encode(texts, show_progress_bar=False)
        return [np.array(v, dtype=np.float32) for v in embs]

# ---------------------------
# FAISS simple store
# ---------------------------
import faiss

class SimpleFAISSStore:
    """Minimal FAISS store mapping vectors -> texts & metadata."""
    def __init__(self, dim: int, index_path: Optional[str] = None):
        self.dim = dim
        self.index = faiss.IndexFlatL2(dim)
        self.ids: List[str] = []
        self.texts: List[str] = []
        self.meta: List[dict] = []
        self.index_path = index_path

    def add(self, vectors: List[np.ndarray], texts: List[str], metas: List[dict], ids: List[str]):
        arr = np.vstack(vectors).astype('float32')
        self.index.add(arr)
        self.ids.extend(ids)
        self.texts.extend(texts)
        self.meta.extend(metas)

    def save(self):
        if self.index_path:
            faiss.write_index(self.index, self.index_path)
            meta_file = self.index_path + '.meta.json'
            with open(meta_file, 'w', encoding='utf-8') as f:
                json.dump({'ids': self.ids, 'texts': self.texts, 'meta': self.meta}, f)

    def search(self, query_vec: np.ndarray, k: int = TOP_K):
        D, I = self.index.search(np.array([query_vec]).astype('float32'), k)
        results = []
        for score, idx in zip(D[0], I[0]):
            if idx < len(self.ids):
                results.append({
                    'id': self.ids[idx],
                    'text': self.texts[idx],
                    'meta': self.meta[idx],
                    'score': float(score)
                })
        return results

# ---------------------------
# Build textbook-only vectorstore
# ---------------------------
def build_textbook_vectorstore(rebuild: bool = False):
    """
    Build FAISS index from the textbook PDF. Returns (store, embedder).
    Will re-create index every run for safety / reproducibility.
    """
    vect_path = os.path.join(VECTORSTORE_DIR, 'textbook.faiss')

    print('Extracting textbook...')
    textbook_text = extract_text_from_pdf(TEXTBOOK_PATH)
    print('Chunking textbook...')
    chunks = chunk_text(textbook_text)
    texts = [c['text'] for c in chunks]
    metas = [c['meta'] for c in chunks]
    ids = [c['id'] for c in chunks]

    print('Embedding chunks (local SentenceTransformer)...')
    embedder = Embedder()
    vectors = embedder.embed_texts(texts)
    dim = vectors[0].shape[0]

    print('Creating FAISS index...')
    store = SimpleFAISSStore(dim=dim, index_path=vect_path)
    store.add(vectors, texts, metas, ids)
    store.save()
    print('Vectorstore created at', vect_path)
    return store, embedder

# ---------------------------
# Generator: Gemini for Q&A (gemini-2.5-flash)
# ---------------------------
class Generator:
    """
    Wrapper around google.generativeai for generation only.
    Expects GEMINI_API_KEY in env or passed before creating this class.
    """
    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
        self.api_key = api_key or os.environ.get('GEMINI_API_KEY')
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY not found in environment and not passed to Generator.")
        try:
            import google.generativeai as genai
            genai.configure(api_key=self.api_key)
            self.genai = genai
            # create a model handle
            try:
                self.model = genai.GenerativeModel(model_name)
            except Exception:
                # some versions may not need class instantiation - still store genai for fallback
                self.model = None
        except Exception as e:
            raise RuntimeError("Failed to import/configure google.generativeai: " + str(e))

    def _call_generate(self, prompt: str) -> str:
        """
        Call the Gemini model in a few fallbacks depending on installed genai version.
        """
        # 1) Preferred: GenerativeModel.generate_content(prompt)
        try:
            if self.model is not None and hasattr(self.model, "generate_content"):
                resp = self.model.generate_content(prompt)
                # resp may have .text or .last depending on version
                return getattr(resp, "text", getattr(resp, "last", str(resp)))
        except Exception:
            pass

        # 2) Alternative: GenerativeModel.generate (some SDK variants)
        try:
            if self.model is not None and hasattr(self.model, "generate"):
                resp = self.model.generate(prompt)
                return getattr(resp, "text", getattr(resp, "last", str(resp)))
        except Exception:
            pass

        # 3) Global helper fallback: genai.generate (older/newer variants)
        try:
            resp = self.genai.generate_text(model="gemini-2.5-flash", prompt=prompt)
            # resp structure varies; try known fields:
            if isinstance(resp, dict):
                return resp.get("candidates", [{}])[0].get("content", resp.get("text", str(resp)))
            return str(resp)
        except Exception:
            pass

        # If all fail, raise a helpful error
        raise RuntimeError("Could not call Gemini generate with the installed google.generativeai package. Check package version and API availability.")

    def generate_answer(self, question: str, contexts: List[dict]) -> str:
        """
        Given a user question and retrieved contexts (list of dicts with 'text' and 'meta'),
        produce an answer that must use ONLY these contexts.
        """
        # Build a grounded prompt that forces the model to rely only on contexts
        context_text = "\n\n-----\n\n".join([f"(Chunk {c.get('meta', {}).get('chunk')}):\n{c['text']}" for c in contexts])
        prompt = (
            "You are an assistant that must answer the user's question using ONLY the evidence in the provided contexts below. "
            "Do NOT use outside knowledge or make up facts. If the context does not contain the answer, reply exactly: 'I cannot answer from the textbook.'\n\n"
            f"CONTEXTS:\n{context_text}\n\nQUESTION: {question}\n\n"
            "Answer succinctly and, when using evidence, append the chunk id in square brackets like [chunk_id]."
        )

        resp_text = self._call_generate(prompt)
        # Normalize output type if object-like
        if not isinstance(resp_text, str):
            resp_text = str(resp_text)
        return resp_text

# ---------------------------
# Query pipeline
# ---------------------------
def answer_question(question: str, store: SimpleFAISSStore, embedder: Embedder, generator: Generator, top_k: int = TOP_K) -> dict:
    """Embed question, retrieve top-k textbook chunks, and generate an answer using generator."""
    qvec = embedder.embed_texts([question])[0]
    hits = store.search(qvec, k=top_k)
    gen_text = generator.generate_answer(question, hits)
    return {'question': question, 'answer': gen_text, 'context_hits': hits}

# ---------------------------
# Concept extraction & paper question search
# ---------------------------
def extract_concepts_from_text(text: str, top_n: int = 3) -> List[str]:
    """Simple noun-chunk or token frequency concept extractor."""
    try:
        import spacy
        nlp = spacy.load('en_core_web_sm')
        doc = nlp(text)
        phrases = [chunk.text.lower() for chunk in doc.noun_chunks]
        if len(phrases) < top_n:
            phrases += [tok.text.lower() for tok in doc if tok.pos_ in ('NOUN', 'PROPN')]
        from collections import Counter
        ctr = Counter(phrases)
        return [p for p, _ in ctr.most_common(top_n)]
    except Exception:
        tokens = [t.strip('.,()').lower() for t in text.split() if len(t) > 3]
        from collections import Counter
        ctr = Counter(tokens)
        return [p for p, _ in ctr.most_common(top_n)]

def extract_questions_from_papers(concepts: List[str], papers_texts: List[Tuple[str, str]], max_questions: int = 10) -> List[dict]:
    """Find question-like sentences in supplied papers that mention any of the concepts."""
    question_sents = []
    for fname, text in papers_texts:
        sents = re.split(r'(?<=[\.!?])\s+', text)
        for s in sents:
            if '?' in s:
                s_low = s.lower()
                for c in concepts:
                    if c.lower() in s_low:
                        question_sents.append({'paper': fname, 'question_sentence': s.strip(), 'concept': c})
                        break
    return question_sents[:max_questions]

# ---------------------------
# If running as a script: quick demo / sanity
# ---------------------------
if __name__ == "__main__":
    print("Building textbook vectorstore (this may take a few minutes)...")
    store, embedder = build_textbook_vectorstore()
    print("Done. Now load papers...")
    papers = extract_texts_from_zip(PAPERS_ZIP_PATH)
    print(f"Loaded {len(papers)} papers.")

    # Try an interactive test loop (simple)
    # Note: Ensure GEMINI_API_KEY is set in env for generation.
    if not os.environ.get('GEMINI_API_KEY'):
        print("Warning: GEMINI_API_KEY not set in environment. Generator will not work without it.")
    else:
        generator = Generator()
        while True:
            q = input("\nEnter a question (or type EXIT): ").strip()
            if not q:
                continue
            if q.upper() in ("EXIT", "QUIT"):
                break
            res = answer_question(q, store, embedder, generator)
            print("\n--- ANSWER ---\n")
            print(res['answer'])
            print("\n--- Retrieved context ids ---\n")
            for h in res['context_hits']:
                print(f"{h['id']} (score={h['score']:.4f}) -> {h['text'][:300].replace('\\n',' ')}...\n")

!pip install streamlit google-generativeai sentence-transformers faiss-cpu pdfplumber tqdm
!npm install -g localtunnel     # For exposing Streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rag_backend.py
# 
# """
# rag_backend.py
# 
# Clean backend for Development Theory RAG system.
# 
# - Local embeddings: sentence-transformers (all-MiniLM-L6-v2)
# - Retrieval: FAISS (IndexFlatL2)
# - Generation: Gemini (gemini-2.5-flash) via google.generativeai (only for generation)
# - Text sources (already uploaded by you):
#     TEXTBOOK_PATH = '/mnt/data/Understanding Development.pdf'
#     PAPERS_ZIP_PATH = '/mnt/data/DevT_Papers.zip'
# """
# 
# import os
# import zipfile
# import json
# from pathlib import Path
# from typing import List, Tuple, Optional
# import re
# 
# # Local file paths (provided by you)
# TEXTBOOK_PATH = '/content/Understanding Development.pdf'
# PAPERS_ZIP_PATH = '/content/DevT_Papers.zip'
# 
# # Vectorstore directory
# VECTORSTORE_DIR = '/content/rag_vectorstore'
# os.makedirs(VECTORSTORE_DIR, exist_ok=True)
# 
# # RAG parameters
# CHUNK_SIZE = 1000
# CHUNK_OVERLAP = 200
# TOP_K = 4
# 
# # Optional: set env var GEMINI_API_KEY for generation (do not hardcode)
# GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
# 
# # ---------------------------
# # Utilities: PDF extraction & chunking
# # ---------------------------
# import pdfplumber
# 
# def extract_text_from_pdf(pdf_path: str) -> str:
#     """Extract full text from a PDF file."""
#     text_parts = []
#     with pdfplumber.open(pdf_path) as pdf:
#         for page in pdf.pages:
#             text = page.extract_text()
#             if text:
#                 text_parts.append(text)
#     return "\n\n".join(text_parts)
# 
# def chunk_text(text: str, chunk_size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> List[dict]:
#     """Deterministic whitespace tokenizer chunker -> list of {'id','text','meta'}."""
#     tokens = text.split()
#     chunks = []
#     idx = 0
#     chunk_id = 0
#     while idx < len(tokens):
#         chunk_tokens = tokens[idx: idx + chunk_size]
#         chunk_text = ' '.join(chunk_tokens)
#         chunks.append({
#             'id': f'textbook_chunk_{chunk_id}',
#             'text': chunk_text,
#             'meta': {'source': TEXTBOOK_PATH, 'chunk': chunk_id}
#         })
#         chunk_id += 1
#         idx += chunk_size - overlap
#     return chunks
# 
# def extract_texts_from_zip(zip_path: str, extract_to: str = '/content/papers_extracted') -> List[Tuple[str, str]]:
#     """Unzip and extract plain text from PDFs and .txt inside the zip. Returns list of (filepath, text)."""
#     os.makedirs(extract_to, exist_ok=True)
#     with zipfile.ZipFile(zip_path, 'r') as z:
#         z.extractall(extract_to)
# 
#     results = []
#     for root, _, files in os.walk(extract_to):
#         for fname in files:
#             full = os.path.join(root, fname)
#             if fname.lower().endswith('.pdf'):
#                 try:
#                     text = extract_text_from_pdf(full)
#                     results.append((full, text))
#                 except Exception as e:
#                     print('Failed to read PDF', full, e)
#             elif fname.lower().endswith('.txt'):
#                 try:
#                     with open(full, 'r', encoding='utf-8', errors='ignore') as f:
#                         results.append((full, f.read()))
#                 except Exception as e:
#                     print('Failed to read txt', full, e)
#     return results
# 
# # ---------------------------
# # Embeddings: sentence-transformers local
# # ---------------------------
# import numpy as np
# 
# class Embedder:
#     """Local sentence-transformers embedder using all-MiniLM-L6-v2."""
#     def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
#         from sentence_transformers import SentenceTransformer
#         self.model = SentenceTransformer(model_name)
# 
#     def embed_texts(self, texts: List[str]) -> List[np.ndarray]:
#         """Return list of numpy float32 vectors for given texts."""
#         # `encode` supports a list to batch; ensure result is 2D
#         embs = self.model.encode(texts, show_progress_bar=False)
#         return [np.array(v, dtype=np.float32) for v in embs]
# 
# # ---------------------------
# # FAISS simple store
# # ---------------------------
# import faiss
# 
# class SimpleFAISSStore:
#     """Minimal FAISS store mapping vectors -> texts & metadata."""
#     def __init__(self, dim: int, index_path: Optional[str] = None):
#         self.dim = dim
#         self.index = faiss.IndexFlatL2(dim)
#         self.ids: List[str] = []
#         self.texts: List[str] = []
#         self.meta: List[dict] = []
#         self.index_path = index_path
# 
#     def add(self, vectors: List[np.ndarray], texts: List[str], metas: List[dict], ids: List[str]):
#         arr = np.vstack(vectors).astype('float32')
#         self.index.add(arr)
#         self.ids.extend(ids)
#         self.texts.extend(texts)
#         self.meta.extend(metas)
# 
#     def save(self):
#         if self.index_path:
#             faiss.write_index(self.index, self.index_path)
#             meta_file = self.index_path + '.meta.json'
#             with open(meta_file, 'w', encoding='utf-8') as f:
#                 json.dump({'ids': self.ids, 'texts': self.texts, 'meta': self.meta}, f)
# 
#     def search(self, query_vec: np.ndarray, k: int = TOP_K):
#         D, I = self.index.search(np.array([query_vec]).astype('float32'), k)
#         results = []
#         for score, idx in zip(D[0], I[0]):
#             if idx < len(self.ids):
#                 results.append({
#                     'id': self.ids[idx],
#                     'text': self.texts[idx],
#                     'meta': self.meta[idx],
#                     'score': float(score)
#                 })
#         return results
# 
# # ---------------------------
# # Build textbook-only vectorstore
# # ---------------------------
# def build_textbook_vectorstore(rebuild: bool = False):
#     """
#     Build FAISS index from the textbook PDF. Returns (store, embedder).
#     Will re-create index every run for safety / reproducibility.
#     """
#     vect_path = os.path.join(VECTORSTORE_DIR, 'textbook.faiss')
# 
#     print('Extracting textbook...')
#     textbook_text = extract_text_from_pdf(TEXTBOOK_PATH)
#     print('Chunking textbook...')
#     chunks = chunk_text(textbook_text)
#     texts = [c['text'] for c in chunks]
#     metas = [c['meta'] for c in chunks]
#     ids = [c['id'] for c in chunks]
# 
#     print('Embedding chunks (local SentenceTransformer)...')
#     embedder = Embedder()
#     vectors = embedder.embed_texts(texts)
#     dim = vectors[0].shape[0]
# 
#     print('Creating FAISS index...')
#     store = SimpleFAISSStore(dim=dim, index_path=vect_path)
#     store.add(vectors, texts, metas, ids)
#     store.save()
#     print('Vectorstore created at', vect_path)
#     return store, embedder
# 
# # ---------------------------
# # Generator: Gemini for Q&A (gemini-2.5-flash)
# # ---------------------------
# class Generator:
#     """
#     Wrapper around google.generativeai for generation only.
#     Expects GEMINI_API_KEY in env or passed before creating this class.
#     """
#     def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
#         self.api_key = api_key or os.environ.get('GEMINI_API_KEY')
#         if not self.api_key:
#             raise ValueError("GEMINI_API_KEY not found in environment and not passed to Generator.")
#         try:
#             import google.generativeai as genai
#             genai.configure(api_key=self.api_key)
#             self.genai = genai
#             # create a model handle
#             try:
#                 self.model = genai.GenerativeModel(model_name)
#             except Exception:
#                 # some versions may not need class instantiation - still store genai for fallback
#                 self.model = None
#         except Exception as e:
#             raise RuntimeError("Failed to import/configure google.generativeai: " + str(e))
# 
#     def _call_generate(self, prompt: str) -> str:
#         """
#         Call the Gemini model in a few fallbacks depending on installed genai version.
#         """
#         # 1) Preferred: GenerativeModel.generate_content(prompt)
#         try:
#             if self.model is not None and hasattr(self.model, "generate_content"):
#                 resp = self.model.generate_content(prompt)
#                 # resp may have .text or .last depending on version
#                 return getattr(resp, "text", getattr(resp, "last", str(resp)))
#         except Exception:
#             pass
# 
#         # 2) Alternative: GenerativeModel.generate (some SDK variants)
#         try:
#             if self.model is not None and hasattr(self.model, "generate"):
#                 resp = self.model.generate(prompt)
#                 return getattr(resp, "text", getattr(resp, "last", str(resp)))
#         except Exception:
#             pass
# 
#         # 3) Global helper fallback: genai.generate (older/newer variants)
#         try:
#             resp = self.genai.generate_text(model="gemini-2.5-flash", prompt=prompt)
#             # resp structure varies; try known fields:
#             if isinstance(resp, dict):
#                 return resp.get("candidates", [{}])[0].get("content", resp.get("text", str(resp)))
#             return str(resp)
#         except Exception:
#             pass
# 
#         # If all fail, raise a helpful error
#         raise RuntimeError("Could not call Gemini generate with the installed google.generativeai package. Check package version and API availability.")
# 
#     def generate_answer(self, question: str, contexts: List[dict]) -> str:
#         """
#         Given a user question and retrieved contexts (list of dicts with 'text' and 'meta'),
#         produce an answer that must use ONLY these contexts.
#         """
#         # Build a grounded prompt that forces the model to rely only on contexts
#         context_text = "\n\n-----\n\n".join([f"(Chunk {c.get('meta', {}).get('chunk')}):\n{c['text']}" for c in contexts])
#         prompt = (
#             "You are an assistant that must answer the user's question using ONLY the evidence in the provided contexts below. "
#             "Do NOT use outside knowledge or make up facts. If the context does not contain the answer, reply exactly: 'I cannot answer from the textbook.'\n\n"
#             f"CONTEXTS:\n{context_text}\n\nQUESTION: {question}\n\n"
#             "Answer succinctly and, when using evidence, append the chunk id in square brackets like [chunk_id]."
#         )
# 
#         resp_text = self._call_generate(prompt)
#         # Normalize output type if object-like
#         if not isinstance(resp_text, str):
#             resp_text = str(resp_text)
#         return resp_text
# 
# # ---------------------------
# # Query pipeline
# # ---------------------------
# def answer_question(question: str, store: SimpleFAISSStore, embedder: Embedder, generator: Generator, top_k: int = TOP_K) -> dict:
#     """Embed question, retrieve top-k textbook chunks, and generate an answer using generator."""
#     qvec = embedder.embed_texts([question])[0]
#     hits = store.search(qvec, k=top_k)
#     gen_text = generator.generate_answer(question, hits)
#     return {'question': question, 'answer': gen_text, 'context_hits': hits}
# 
# # ---------------------------
# # Concept extraction & paper question search
# # ---------------------------
# def extract_concepts_from_text(text: str, top_n: int = 3) -> List[str]:
#     """Simple noun-chunk or token frequency concept extractor."""
#     try:
#         import spacy
#         nlp = spacy.load('en_core_web_sm')
#         doc = nlp(text)
#         phrases = [chunk.text.lower() for chunk in doc.noun_chunks]
#         if len(phrases) < top_n:
#             phrases += [tok.text.lower() for tok in doc if tok.pos_ in ('NOUN', 'PROPN')]
#         from collections import Counter
#         ctr = Counter(phrases)
#         return [p for p, _ in ctr.most_common(top_n)]
#     except Exception:
#         tokens = [t.strip('.,()').lower() for t in text.split() if len(t) > 3]
#         from collections import Counter
#         ctr = Counter(tokens)
#         return [p for p, _ in ctr.most_common(top_n)]
# 
# def extract_questions_from_papers(concepts: List[str], papers_texts: List[Tuple[str, str]], max_questions: int = 10) -> List[dict]:
#     """Find question-like sentences in supplied papers that mention any of the concepts."""
#     question_sents = []
#     for fname, text in papers_texts:
#         sents = re.split(r'(?<=[\.!?])\s+', text)
#         for s in sents:
#             if '?' in s:
#                 s_low = s.lower()
#                 for c in concepts:
#                     if c.lower() in s_low:
#                         question_sents.append({'paper': fname, 'question_sentence': s.strip(), 'concept': c})
#                         break
#     return question_sents[:max_questions]
# 
# # ---------------------------
# # If running as a script: quick demo / sanity
# # ---------------------------
# if __name__ == "__main__":
#     print("Building textbook vectorstore (this may take a few minutes)...")
#     store, embedder = build_textbook_vectorstore()
#     print("Done. Now load papers...")
#     papers = extract_texts_from_zip(PAPERS_ZIP_PATH)
#     print(f"Loaded {len(papers)} papers.")
# 
#     # Try an interactive test loop (simple)
#     # Note: Ensure GEMINI_API_KEY is set in env for generation.
#     if not os.environ.get('GEMINI_API_KEY'):
#         print("Warning: GEMINI_API_KEY not set in environment. Generator will not work without it.")
#     else:
#         generator = Generator()
#         while True:
#             q = input("\nEnter a question (or type EXIT): ").strip()
#             if not q:
#                 continue
#             if q.upper() in ("EXIT", "QUIT"):
#                 break
#             res = answer_question(q, store, embedder, generator)
#             print("\n--- ANSWER ---\n")
#             print(res['answer'])
#             print("\n--- Retrieved context ids ---\n")
#             for h in res['context_hits']:
#                 print(f"{h['id']} (score={h['score']:.4f}) -> {h['text'][:300].replace('\\n',' ')}...\n")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ui.py
# 
# import streamlit as st
# from rag_backend import (
#     build_textbook_vectorstore,
#     answer_question,
#     extract_concepts_from_text,
#     extract_questions_from_papers,
#     extract_texts_from_zip,
#     PAPERS_ZIP_PATH,
#     Generator
# )
# 
# import os
# 
# # -----------------------------------
# # PAGE CONFIG
# # -----------------------------------
# st.set_page_config(
#     page_title="Development Theory RAG",
#     layout="wide",
#     page_icon="📘"
# )
# 
# st.title("📘 Development Theory RAG System")
# st.markdown("""
# Ask **any Development Theory question**.
# This system will answer using **only the textbook**, then show **related past-year exam questions**.
# """)
# 
# # -----------------------------------
# # LOAD VECTORSTORE + PAPERS (cached)
# # -----------------------------------
# @st.cache_resource(show_spinner=True)
# def load_backend():
#     st.info("Building vectorstore... This will run only once.")
#     store, embedder = build_textbook_vectorstore()
#     papers = extract_texts_from_zip(PAPERS_ZIP_PATH)
#     return store, embedder, papers
# 
# store, embedder, papers_texts = load_backend()
# 
# # -----------------------------------
# # Gemini API KEY
# # -----------------------------------
# st.sidebar.header("🔑 Gemini API Key")
# api_key = st.sidebar.text_input(
#     "Enter your Gemini API Key",
#     type="password",
#     help="Key is NOT stored. Needed for generating answers."
# )
# 
# generator = None
# if api_key:
#     os.environ["GEMINI_API_KEY"] = api_key
#     try:
#         generator = Generator(api_key=api_key)
#     except Exception as e:
#         st.sidebar.error(f"Generator init failed: {e}")
# 
# else:
#     st.sidebar.warning("Enter your Gemini API key to enable answer generation.")
# 
# # -----------------------------------
# # QUESTION INPUT
# # -----------------------------------
# st.subheader("🔹 Ask Your Question")
# 
# question = st.text_area(
#     "Enter your question here:",
#     height=120,
#     placeholder="Example: Explain the concept of laissez-faire economy"
# )
# 
# # -----------------------------------
# # PROCESS BUTTON
# # -----------------------------------
# if st.button("Get Answer", use_container_width=True):
# 
#     if not api_key:
#         st.error("Please enter your Gemini API Key first.")
#     elif not question.strip():
#         st.warning("Please enter a question.")
#     else:
#         with st.spinner("Retrieving best chunks and generating answer..."):
#             result = answer_question(question, store, embedder, generator)
# 
#         # -----------------------------------
#         # ANSWER SECTION
#         # -----------------------------------
#         st.subheader("📗 Answer (from textbook only)")
#         st.write(result["answer"])
# 
#         # -----------------------------------
#         # RETRIEVED CHUNKS
#         # -----------------------------------
#         st.subheader("📌 Retrieved Textbook Chunks Used")
#         for hit in result["context_hits"]:
#             with st.expander(f"{hit['id']}  (score: {hit['score']:.4f})"):
#                 st.write(hit["text"])
# 
#         # -----------------------------------
#         # CONCEPT EXTRACTION
#         # -----------------------------------
#         concepts = extract_concepts_from_text(result["answer"])
#         st.subheader("🧠 Identified Key Concepts")
#         st.write(concepts)
# 
#         # -----------------------------------
#         # RELATED EXAM QUESTIONS
#         # -----------------------------------
#         st.subheader("📝 Related Past-Year Questions")
#         related = extract_questions_from_papers(concepts, papers_texts)
# 
#         if related:
#             for q in related:
#                 st.markdown(f"**• ({q['paper'].split('/')[-1]})** {q['question_sentence']}")
#         else:
#             st.info("No related past-year questions found.")
#

!streamlit run ui.py & npx localtunnel --port 8501

